import os
from base64 import b64encode

import requests
from dotenv import load_dotenv
import csv

load_dotenv('.env')


class CompaniesHouseConnector:

    def __init__(self):
        self.base_url = os.environ['COMPANY_HOUSE_BASE_URL']
        self.__api_key = os.environ['API_KEY']

    def get_auth(self):
        return 'Basic ' + b64encode(f'{self.__api_key}:'.encode('UTF-8')).decode()

    def get_request_headers(self):

        return {
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'Authorization': self.get_auth()
        }

    def search_companies(self, search_term, items_per_page=5, start_index=0):
        """
        Search for companies based on the given search term.

        Parameters:
        - search_term (str): The term to search for.
        - items_per_page (int): Number of items to retrieve per page.
        - start_index (int): Starting index for the search.

        Returns:
        - dict: Parsed JSON response from the API.
        """
        endpoint = f'search?q={search_term}&items_per_page={items_per_page}&start_index={start_index}'
        try:
            response = requests.get(
                url=self.base_url + endpoint,
                headers=self.get_request_headers()
            )
            response.raise_for_status()  # Raise HTTPError for bad responses
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error during API request: {e}")
            return None  # Or raise an exception or handle it accordingly

    def get_registered_office_address(self, company_number):
        """

        :param company_number:
        :return:
        """
        endpoint = f'company/{company_number}/registered-office-address'
        try:
            response = requests.get(
                url=self.base_url + endpoint,
                headers=self.get_request_headers()
            )
            response.raise_for_status()  # Raise HTTPError for bad responses
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error during API request: {e}")
            return None  # Or raise an exception or handle it accordingly

    def get_company_profile(self, company_number):

        endpoint = f'company/{company_number}'
        try:
            response = requests.get(
                url=self.base_url + endpoint,
                headers=self.get_request_headers()
            )
            response.raise_for_status()  # Raise HTTPError for bad responses
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error during API request: {e}")
            return None  # Or raise an exception or handle it accordingly


class CompanyCollection:

    def __init__(self):
        self.companies = []

    def add_company(self, company):
        self.companies.append(company)
        return self

    def read_from_csv(self, path):
        try:
            with open(path, 'r') as file:
                reader = csv.DictReader(file)
                for row in reader:
                    self.companies.append({
                        'name': row.get('Organisation Name', ''),
                        'address': '',
                        'city': row.get('Town/City', ''),
                        'county': row.get('County', ''),
                        'post_code': '',
                        'type_and_rating': row.get('Type & Rating', ''),
                        'route': row.get('Route', '')
                    })
        except FileNotFoundError:
            print(f"Error: File not found at path {path}")
        except csv.Error as e:
            print(f"Error reading CSV file at {path}: {e}")

    def get_companies(self):
        return self.companies


class CompanyHouseHelper:
    SIC_CODE_MAPPING = {
        '01110': 'Agriculture, Forestry and Fishing',
        '01120': 'Agriculture, Forestry and Fishing',
        '01130': 'Agriculture, Forestry and Fishing',
        '01140': 'Agriculture, Forestry and Fishing',
        '01150': 'Agriculture, Forestry and Fishing',
        '01160': 'Agriculture, Forestry and Fishing',
        '01190': 'Agriculture, Forestry and Fishing',
        '01210': 'Agriculture, Forestry and Fishing',
        '01220': 'Agriculture, Forestry and Fishing',
        '01230': 'Agriculture, Forestry and Fishing',
        '01240': 'Agriculture, Forestry and Fishing',
        '01250': 'Agriculture, Forestry and Fishing',
        '01260': 'Agriculture, Forestry and Fishing',
        '01270': 'Agriculture, Forestry and Fishing',
        '01280': 'Agriculture, Forestry and Fishing',
        '01290': 'Agriculture, Forestry and Fishing',
        '01300': 'Agriculture, Forestry and Fishing',
        '01410': 'Agriculture, Forestry and Fishing',
        '01420': 'Agriculture, Forestry and Fishing',
        '01430': 'Agriculture, Forestry and Fishing',
        '01440': 'Agriculture, Forestry and Fishing',
        '01450': 'Agriculture, Forestry and Fishing',
        '01460': 'Agriculture, Forestry and Fishing',
        '01470': 'Agriculture, Forestry and Fishing',
        '01490': 'Agriculture, Forestry and Fishing',
        '01500': 'Agriculture, Forestry and Fishing',
        '01610': 'Agriculture, Forestry and Fishing',
        '01621': 'Agriculture, Forestry and Fishing',
        '01629': 'Agriculture, Forestry and Fishing',
        '01630': 'Agriculture, Forestry and Fishing',
        '01640': 'Agriculture, Forestry and Fishing',
        '01700': 'Agriculture, Forestry and Fishing',
        '02100': 'Agriculture, Forestry and Fishing',
        '02200': 'Agriculture, Forestry and Fishing',
        '02300': 'Agriculture, Forestry and Fishing',
        '02400': 'Agriculture, Forestry and Fishing',
        '03110': 'Agriculture, Forestry and Fishing',
        '03120': 'Agriculture, Forestry and Fishing',
        '03210': 'Agriculture, Forestry and Fishing',
        '03220': 'Agriculture, Forestry and Fishing',
        '05101': 'Mining and Quarrying',
        '05102': 'Mining and Quarrying',
        '05200': 'Mining and Quarrying',
        '06100': 'Mining and Quarrying',
        '06200': 'Mining and Quarrying',
        '07100': 'Mining and Quarrying',
        '07210': 'Mining and Quarrying',
        '07290': 'Mining and Quarrying',
        '08110': 'Mining and Quarrying',
        '08120': 'Mining and Quarrying',
        '08910': 'Mining and Quarrying',
        '08920': 'Mining and Quarrying',
        '08930': 'Mining and Quarrying',
        '08990': 'Mining and Quarrying',
        '09100': 'Mining and Quarrying',
        '09900': 'Mining and Quarrying',
        '10110': 'Manufacturing',
        '10120': 'Manufacturing',
        '10130': 'Manufacturing',
        '10200': 'Manufacturing',
        '10310': 'Manufacturing',
        '10320': 'Manufacturing',
        '10390': 'Manufacturing',
        '10410': 'Manufacturing',
        '10420': 'Manufacturing',
        '10511': 'Manufacturing',
        '10512': 'Manufacturing',
        '10519': 'Manufacturing',
        '10520': 'Manufacturing',
        '10611': 'Manufacturing',
        '10612': 'Manufacturing',
        '10620': 'Manufacturing',
        '10710': 'Manufacturing',
        '10720': 'Manufacturing',
        '10730': 'Manufacturing',
        '10810': 'Manufacturing',
        '10821': 'Manufacturing',
        '10822': 'Manufacturing',
        '10831': 'Manufacturing',
        '10832': 'Manufacturing',
        '10840': 'Manufacturing',
        '10850': 'Manufacturing',
        '10860': 'Manufacturing',
        '10890': 'Manufacturing',
        '10910': 'Manufacturing',
        '10920': 'Manufacturing',
        '11010': 'Manufacturing',
        '11020': 'Manufacturing',
        '11030': 'Manufacturing',
        '11040': 'Manufacturing',
        '11050': 'Manufacturing',
        '11060': 'Manufacturing',
        '11070': 'Manufacturing',
        '12000': 'Manufacturing',
        '13100': 'Manufacturing',
        '13200': 'Manufacturing',
        '13300': 'Manufacturing',
        '13910': 'Manufacturing',
        '13921': 'Manufacturing',
        '13922': 'Manufacturing',
        '13923': 'Manufacturing',
        '13931': 'Manufacturing',
        '13939': 'Manufacturing',
        '13940': 'Manufacturing',
        '13950': 'Manufacturing',
        '13960': 'Manufacturing',
        '13990': 'Manufacturing',
        '14110': 'Manufacturing',
        '14120': 'Manufacturing',
        '14131': 'Manufacturing',
        '14132': 'Manufacturing',
        '14141': 'Manufacturing',
        '14142': 'Manufacturing',
        '14190': 'Manufacturing',
        '14200': 'Manufacturing',
        '14310': 'Manufacturing',
        '14390': 'Manufacturing',
        '15110': 'Manufacturing',
        '15120': 'Manufacturing',
        '15200': 'Manufacturing',
        '16100': 'Manufacturing',
        '16210': 'Manufacturing',
        '16220': 'Manufacturing',
        '16230': 'Manufacturing',
        '16240': 'Manufacturing',
        '16290': 'Manufacturing',
        '17110': 'Manufacturing',
        '17120': 'Manufacturing',
        '17211': 'Manufacturing',
        '17219': 'Manufacturing',
        '17220': 'Manufacturing',
        '17230': 'Manufacturing',
        '17240': 'Manufacturing',
        '17290': 'Manufacturing',
        '18110': 'Manufacturing',
        '18121': 'Manufacturing',
        '18129': 'Manufacturing',
        '18130': 'Manufacturing',
        '18140': 'Manufacturing',
        '18201': 'Manufacturing',
        '18202': 'Manufacturing',
        '18203': 'Manufacturing',
        '19100': 'Manufacturing',
        '19201': 'Manufacturing',
        '19209': 'Manufacturing',
        '20110': 'Manufacturing',
        '20120': 'Manufacturing',
        '20130': 'Manufacturing',
        '20140': 'Manufacturing',
        '20150': 'Manufacturing',
        '20160': 'Manufacturing',
        '20170': 'Manufacturing',
        '20200': 'Manufacturing',
        '20301': 'Manufacturing',
        '20302': 'Manufacturing',
        '20411': 'Manufacturing',
        '20412': 'Manufacturing',
        '20420': 'Manufacturing',
        '20510': 'Manufacturing',
        '20520': 'Manufacturing',
        '20530': 'Manufacturing',
        '20590': 'Manufacturing',
        '20600': 'Manufacturing',
        '21100': 'Manufacturing',
        '21200': 'Manufacturing',
        '22110': 'Manufacturing',
        '22190': 'Manufacturing',
        '22210': 'Manufacturing',
        '22220': 'Manufacturing',
        '22230': 'Manufacturing',
        '22290': 'Manufacturing',
        '23110': 'Manufacturing',
        '23120': 'Manufacturing',
        '23130': 'Manufacturing',
        '23140': 'Manufacturing',
        '23190': 'Manufacturing',
        '23200': 'Manufacturing',
        '23310': 'Manufacturing',
        '23320': 'Manufacturing',
        '23410': 'Manufacturing',
        '23420': 'Manufacturing',
        '23430': 'Manufacturing',
        '23440': 'Manufacturing',
        '23490': 'Manufacturing',
        '23510': 'Manufacturing',
        '23520': 'Manufacturing',
        '23610': 'Manufacturing',
        '23620': 'Manufacturing',
        '23630': 'Manufacturing',
        '23640': 'Manufacturing',
        '23650': 'Manufacturing',
        '23690': 'Manufacturing',
        '23700': 'Manufacturing',
        '23910': 'Manufacturing',
        '23990': 'Manufacturing',
        '24100': 'Manufacturing',
        '24200': 'Manufacturing',
        '24310': 'Manufacturing',
        '24320': 'Manufacturing',
        '24330': 'Manufacturing',
        '24340': 'Manufacturing',
        '24410': 'Manufacturing',
        '24420': 'Manufacturing',
        '24430': 'Manufacturing',
        '24440': 'Manufacturing',
        '24450': 'Manufacturing',
        '24460': 'Manufacturing',
        '24510': 'Manufacturing',
        '24520': 'Manufacturing',
        '24530': 'Manufacturing',
        '24540': 'Manufacturing',
        '25110': 'Manufacturing',
        '25120': 'Manufacturing',
        '25210': 'Manufacturing',
        '25290': 'Manufacturing',
        '25300': 'Manufacturing',
        '25400': 'Manufacturing',
        '25500': 'Manufacturing',
        '25610': 'Manufacturing',
        '25620': 'Manufacturing',
        '25710': 'Manufacturing',
        '25720': 'Manufacturing',
        '25730': 'Manufacturing',
        '25910': 'Manufacturing',
        '25920': 'Manufacturing',
        '25930': 'Manufacturing',
        '25940': 'Manufacturing',
        '25990': 'Manufacturing',
        '26110': 'Manufacturing',
        '26120': 'Manufacturing',
        '26200': 'Manufacturing',
        '26301': 'Manufacturing',
        '26309': 'Manufacturing',
        '26400': 'Manufacturing',
        '26511': 'Manufacturing',
        '26512': 'Manufacturing',
        '26513': 'Manufacturing',
        '26514': 'Manufacturing',
        '26520': 'Manufacturing',
        '26600': 'Manufacturing',
        '26701': 'Manufacturing',
        '26702': 'Manufacturing',
        '26800': 'Manufacturing',
        '27110': 'Manufacturing',
        '27120': 'Manufacturing',
        '27200': 'Manufacturing',
        '27310': 'Manufacturing',
        '27320': 'Manufacturing',
        '27330': 'Manufacturing',
        '27400': 'Manufacturing',
        '27510': 'Manufacturing',
        '27520': 'Manufacturing',
        '27900': 'Manufacturing',
        '28110': 'Manufacturing',
        '28120': 'Manufacturing',
        '28131': 'Manufacturing',
        '28132': 'Manufacturing',
        '28140': 'Manufacturing',
        '28150': 'Manufacturing',
        '28210': 'Manufacturing',
        '28220': 'Manufacturing',
        '28230': 'Manufacturing',
        '28240': 'Manufacturing',
        '28250': 'Manufacturing',
        '28290': 'Manufacturing',
        '28301': 'Manufacturing',
        '28302': 'Manufacturing',
        '28410': 'Manufacturing',
        '28490': 'Manufacturing',
        '28910': 'Manufacturing',
        '28921': 'Manufacturing',
        '28922': 'Manufacturing',
        '28923': 'Manufacturing',
        '28930': 'Manufacturing',
        '28940': 'Manufacturing',
        '28950': 'Manufacturing',
        '28960': 'Manufacturing',
        '28990': 'Manufacturing',
        '29100': 'Manufacturing',
        '29201': 'Manufacturing',
        '29202': 'Manufacturing',
        '29203': 'Manufacturing',
        '29310': 'Manufacturing',
        '29320': 'Manufacturing',
        '30110': 'Manufacturing',
        '30120': 'Manufacturing',
        '30200': 'Manufacturing',
        '30300': 'Manufacturing',
        '30400': 'Manufacturing',
        '30910': 'Manufacturing',
        '30920': 'Manufacturing',
        '30990': 'Manufacturing',
        '31010': 'Manufacturing',
        '31020': 'Manufacturing',
        '31030': 'Manufacturing',
        '31090': 'Manufacturing',
        '32110': 'Manufacturing',
        '32120': 'Manufacturing',
        '32130': 'Manufacturing',
        '32200': 'Manufacturing',
        '32300': 'Manufacturing',
        '32401': 'Manufacturing',
        '32409': 'Manufacturing',
        '32500': 'Manufacturing',
        '32910': 'Manufacturing',
        '32990': 'Manufacturing',
        '33110': 'Manufacturing',
        '33120': 'Manufacturing',
        '33130': 'Manufacturing',
        '33140': 'Manufacturing',
        '33150': 'Manufacturing',
        '33160': 'Manufacturing',
        '33170': 'Manufacturing',
        '33190': 'Manufacturing',
        '33200': 'Manufacturing',
        '35110': 'Electricity, gas, steam and air conditioning supply',
        '35120': 'Electricity, gas, steam and air conditioning supply',
        '35130': 'Electricity, gas, steam and air conditioning supply',
        '35140': 'Electricity, gas, steam and air conditioning supply',
        '35210': 'Electricity, gas, steam and air conditioning supply',
        '35220': 'Electricity, gas, steam and air conditioning supply',
        '35230': 'Electricity, gas, steam and air conditioning supply',
        '35300': 'Electricity, gas, steam and air conditioning supply',
        '36000': 'Water supply, sewerage, waste management and remediation activities',
        '37000': 'Water supply, sewerage, waste management and remediation activities',
        '38110': 'Water supply, sewerage, waste management and remediation activities',
        '38120': 'Water supply, sewerage, waste management and remediation activities',
        '38210': 'Water supply, sewerage, waste management and remediation activities',
        '38220': 'Water supply, sewerage, waste management and remediation activities',
        '38310': 'Water supply, sewerage, waste management and remediation activities',
        '38320': 'Water supply, sewerage, waste management and remediation activities',
        '39000': 'Water supply, sewerage, waste management and remediation activities',
        '41100': 'Construction',
        '41201': 'Construction',
        '41202': 'Construction',
        '42110': 'Construction',
        '42120': 'Construction',
        '42130': 'Construction',
        '42210': 'Construction',
        '42220': 'Construction',
        '42910': 'Construction',
        '42990': 'Construction',
        '43110': 'Construction',
        '43120': 'Construction',
        '43130': 'Construction',
        '43210': 'Construction',
        '43220': 'Construction',
        '43290': 'Construction',
        '43310': 'Construction',
        '43320': 'Construction',
        '43330': 'Construction',
        '43341': 'Construction',
        '43342': 'Construction',
        '43390': 'Construction',
        '43910': 'Construction',
        '43991': 'Construction',
        '43999': 'Construction',
        '45111': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '45112': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '45190': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '45200': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '45310': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '45320': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '45400': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46110': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46120': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46130': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46140': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46150': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46160': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46170': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46180': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46190': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46210': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46220': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46230': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46240': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46310': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46320': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46330': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46341': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46342': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46350': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46360': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46370': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46380': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46390': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46410': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46420': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46431': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46439': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46440': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46450': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46460': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46470': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46480': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46491': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46499': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46510': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46520': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46610': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46620': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46630': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46640': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46650': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46660': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46690': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46711': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46719': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46720': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46730': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46740': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46750': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46760': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46770': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '46900': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47110': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47190': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47210': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47220': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47230': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47240': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47250': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47260': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47290': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47300': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47410': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47421': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47429': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47430': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47510': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47520': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47530': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47540': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47591': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47599': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47610': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47620': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47630': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47640': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47650': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47710': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47721': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47722': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47730': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47741': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47749': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47750': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47760': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47770': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47781': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47782': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47789': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47791': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47799': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47810': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47820': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47890': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47910': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '47990': 'Wholesale and retail trade; repair of motor vehicles and motorcycles',
        '49100': 'Transportation and storage',
        '49200': 'Transportation and storage',
        '49311': 'Transportation and storage',
        '49319': 'Transportation and storage',
        '49320': 'Transportation and storage',
        '49390': 'Transportation and storage',
        '49410': 'Transportation and storage',
        '49420': 'Transportation and storage',
        '49500': 'Transportation and storage',
        '50100': 'Transportation and storage',
        '50200': 'Transportation and storage',
        '50300': 'Transportation and storage',
        '50400': 'Transportation and storage',
        '51101': 'Transportation and storage',
        '51102': 'Transportation and storage',
        '51210': 'Transportation and storage',
        '51220': 'Transportation and storage',
        '52101': 'Transportation and storage',
        '52102': 'Transportation and storage',
        '52103': 'Transportation and storage',
        '52211': 'Transportation and storage',
        '52212': 'Transportation and storage',
        '52213': 'Transportation and storage',
        '52219': 'Transportation and storage',
        '52220': 'Transportation and storage',
        '52230': 'Transportation and storage',
        '52241': 'Transportation and storage',
        '52242': 'Transportation and storage',
        '52243': 'Transportation and storage',
        '52290': 'Transportation and storage',
        '53100': 'Transportation and storage',
        '53201': 'Transportation and storage',
        '53202': 'Transportation and storage',
        '55100': 'Accommodation and food service activities',
        '55201': 'Accommodation and food service activities',
        '55202': 'Accommodation and food service activities',
        '55209': 'Accommodation and food service activities',
        '55300': 'Accommodation and food service activities',
        '55900': 'Accommodation and food service activities',
        '56101': 'Accommodation and food service activities',
        '56102': 'Accommodation and food service activities',
        '56103': 'Accommodation and food service activities',
        '56210': 'Accommodation and food service activities',
        '56290': 'Accommodation and food service activities',
        '56301': 'Accommodation and food service activities',
        '56302': 'Accommodation and food service activities',
        '58110': 'Information and communication',
        '58120': 'Information and communication',
        '58130': 'Information and communication',
        '58141': 'Information and communication',
        '58142': 'Information and communication',
        '58190': 'Information and communication',
        '58210': 'Information and communication',
        '58290': 'Information and communication',
        '59111': 'Information and communication',
        '59112': 'Information and communication',
        '59113': 'Information and communication',
        '59120': 'Information and communication',
        '59131': 'Information and communication',
        '59132': 'Information and communication',
        '59133': 'Information and communication',
        '59140': 'Information and communication',
        '59200': 'Information and communication',
        '60100': 'Information and communication',
        '60200': 'Information and communication',
        '61100': 'Information and communication',
        '61200': 'Information and communication',
        '61300': 'Information and communication',
        '61900': 'Information and communication',
        '62011': 'Information and communication',
        '62012': 'Information and communication',
        '62020': 'Information and communication',
        '62030': 'Information and communication',
        '62090': 'Information and communication',
        '63110': 'Information and communication',
        '63120': 'Information and communication',
        '63910': 'Information and communication',
        '63990': 'Information and communication',
        '64110': 'Financial and insurance activities',
        '64191': 'Financial and insurance activities',
        '64192': 'Financial and insurance activities',
        '64201': 'Financial and insurance activities',
        '64202': 'Financial and insurance activities',
        '64203': 'Financial and insurance activities',
        '64204': 'Financial and insurance activities',
        '64205': 'Financial and insurance activities',
        '64209': 'Financial and insurance activities',
        '64301': 'Financial and insurance activities',
        '64302': 'Financial and insurance activities',
        '64303': 'Financial and insurance activities',
        '64304': 'Financial and insurance activities',
        '64305': 'Financial and insurance activities',
        '64306': 'Financial and insurance activities',
        '64910': 'Financial and insurance activities',
        '64921': 'Financial and insurance activities',
        '64922': 'Financial and insurance activities',
        '64929': 'Financial and insurance activities',
        '64991': 'Financial and insurance activities',
        '64992': 'Financial and insurance activities',
        '64999': 'Financial and insurance activities',
        '65110': 'Financial and insurance activities',
        '65120': 'Financial and insurance activities',
        '65201': 'Financial and insurance activities',
        '65202': 'Financial and insurance activities',
        '65300': 'Financial and insurance activities',
        '66110': 'Financial and insurance activities',
        '66120': 'Financial and insurance activities',
        '66190': 'Financial and insurance activities',
        '66210': 'Financial and insurance activities',
        '66220': 'Financial and insurance activities',
        '66290': 'Financial and insurance activities',
        '66300': 'Financial and insurance activities',
        '68100': 'Real estate activities',
        '68201': 'Real estate activities',
        '68202': 'Real estate activities',
        '68209': 'Real estate activities',
        '68310': 'Real estate activities',
        '68320': 'Real estate activities',
        '69101': 'Professional, scientific and technical activities',
        '69102': 'Professional, scientific and technical activities',
        '69109': 'Professional, scientific and technical activities',
        '69201': 'Professional, scientific and technical activities',
        '69202': 'Professional, scientific and technical activities',
        '69203': 'Professional, scientific and technical activities',
        '70100': 'Professional, scientific and technical activities',
        '70210': 'Professional, scientific and technical activities',
        '70221': 'Professional, scientific and technical activities',
        '70229': 'Professional, scientific and technical activities',
        '71111': 'Professional, scientific and technical activities',
        '71112': 'Professional, scientific and technical activities',
        '71121': 'Professional, scientific and technical activities',
        '71122': 'Professional, scientific and technical activities',
        '71129': 'Professional, scientific and technical activities',
        '71200': 'Professional, scientific and technical activities',
        '72110': 'Professional, scientific and technical activities',
        '72190': 'Professional, scientific and technical activities',
        '72200': 'Professional, scientific and technical activities',
        '73110': 'Professional, scientific and technical activities',
        '73120': 'Professional, scientific and technical activities',
        '73200': 'Professional, scientific and technical activities',
        '74100': 'Professional, scientific and technical activities',
        '74201': 'Professional, scientific and technical activities',
        '74202': 'Professional, scientific and technical activities',
        '74203': 'Professional, scientific and technical activities',
        '74209': 'Professional, scientific and technical activities',
        '74300': 'Professional, scientific and technical activities',
        '74901': 'Professional, scientific and technical activities',
        '74902': 'Professional, scientific and technical activities',
        '74909': 'Professional, scientific and technical activities',
        '74990': 'Professional, scientific and technical activities',
        '75000': 'Professional, scientific and technical activities',
        '77110': 'Administrative and support service activities',
        '77120': 'Administrative and support service activities',
        '77210': 'Administrative and support service activities',
        '77220': 'Administrative and support service activities',
        '77291': 'Administrative and support service activities',
        '77299': 'Administrative and support service activities',
        '77310': 'Administrative and support service activities',
        '77320': 'Administrative and support service activities',
        '77330': 'Administrative and support service activities',
        '77341': 'Administrative and support service activities',
        '77342': 'Administrative and support service activities',
        '77351': 'Administrative and support service activities',
        '77352': 'Administrative and support service activities',
        '77390': 'Administrative and support service activities',
        '77400': 'Administrative and support service activities',
        '78101': 'Administrative and support service activities',
        '78109': 'Administrative and support service activities',
        '78200': 'Administrative and support service activities',
        '78300': 'Administrative and support service activities',
        '79110': 'Administrative and support service activities',
        '79120': 'Administrative and support service activities',
        '79901': 'Administrative and support service activities',
        '79909': 'Administrative and support service activities',
        '80100': 'Administrative and support service activities',
        '80200': 'Administrative and support service activities',
        '80300': 'Administrative and support service activities',
        '81100': 'Administrative and support service activities',
        '81210': 'Administrative and support service activities',
        '81221': 'Administrative and support service activities',
        '81222': 'Administrative and support service activities',
        '81223': 'Administrative and support service activities',
        '81229': 'Administrative and support service activities',
        '81291': 'Administrative and support service activities',
        '81299': 'Administrative and support service activities',
        '81300': 'Administrative and support service activities',
        '82110': 'Administrative and support service activities',
        '82190': 'Administrative and support service activities',
        '82200': 'Administrative and support service activities',
        '82301': 'Administrative and support service activities',
        '82302': 'Administrative and support service activities',
        '82911': 'Administrative and support service activities',
        '82912': 'Administrative and support service activities',
        '82920': 'Administrative and support service activities',
        '82990': 'Administrative and support service activities',
        '84110': 'Public administration and defence; compulsory social security',
        '84120': 'Public administration and defence; compulsory social security',
        '84130': 'Public administration and defence; compulsory social security',
        '84210': 'Public administration and defence; compulsory social security',
        '84220': 'Public administration and defence; compulsory social security',
        '84230': 'Public administration and defence; compulsory social security',
        '84240': 'Public administration and defence; compulsory social security',
        '84250': 'Public administration and defence; compulsory social security',
        '84300': 'Public administration and defence; compulsory social security',
        '85100': 'Education',
        '85200': 'Education',
        '85310': 'Education',
        '85320': 'Education',
        '85410': 'Education',
        '85421': 'Education',
        '85422': 'Education',
        '85510': 'Education',
        '85520': 'Education',
        '85530': 'Education',
        '85590': 'Education',
        '85600': 'Education',
        '86101': 'Human health and social work activities',
        '86102': 'Human health and social work activities',
        '86210': 'Human health and social work activities',
        '86220': 'Human health and social work activities',
        '86230': 'Human health and social work activities',
        '86900': 'Human health and social work activities',
        '87100': 'Human health and social work activities',
        '87200': 'Human health and social work activities',
        '87300': 'Human health and social work activities',
        '87900': 'Human health and social work activities',
        '88100': 'Human health and social work activities',
        '88910': 'Human health and social work activities',
        '88990': 'Human health and social work activities',
        '90010': 'Arts, entertainment and recreation',
        '90020': 'Arts, entertainment and recreation',
        '90030': 'Arts, entertainment and recreation',
        '90040': 'Arts, entertainment and recreation',
        '91011': 'Arts, entertainment and recreation',
        '91012': 'Arts, entertainment and recreation',
        '91020': 'Arts, entertainment and recreation',
        '91030': 'Arts, entertainment and recreation',
        '91040': 'Arts, entertainment and recreation',
        '92000': 'Arts, entertainment and recreation',
        '93110': 'Arts, entertainment and recreation',
        '93120': 'Arts, entertainment and recreation',
        '93130': 'Arts, entertainment and recreation',
        '93191': 'Arts, entertainment and recreation',
        '93199': 'Arts, entertainment and recreation',
        '93210': 'Arts, entertainment and recreation',
        '93290': 'Arts, entertainment and recreation',
        '94110': 'Other service activities',
        '94120': 'Other service activities',
        '94200': 'Other service activities',
        '94910': 'Other service activities',
        '94920': 'Other service activities',
        '94990': 'Other service activities',
        '95110': 'Other service activities',
        '95120': 'Other service activities',
        '95210': 'Other service activities',
        '95220': 'Other service activities',
        '95230': 'Other service activities',
        '95240': 'Other service activities',
        '95250': 'Other service activities',
        '95290': 'Other service activities',
        '96010': 'Other service activities',
        '96020': 'Other service activities',
        '96030': 'Other service activities',
        '96040': 'Other service activities',
        '96090': 'Other service activities',
        '97000': 'Activities of households as employers;',
        '98000': 'Activities of households as employers;',
        '98100': 'Activities of households as employers;',
        '98200': 'Activities of households as employers;',
        '99000': 'Activities of extraterritorial organisations and bodies',
        '99999': 'Activities of extraterritorial organisations and bodies',
    }

    @staticmethod
    def get_sic_code_mapping(code):
        """
                Get the description associated with the given SIC code.

                Args:
                    code (str): The SIC code.

                Returns:
                    str: The description associated with the SIC code, or an empty string if not found.
                """
        return CompanyHouseHelper.SIC_CODE_MAPPING.get(code, '')
